apiVersion: v1
kind: Service
metadata:
  name: user-center
  namespace: demo
spec:
  selector:
    app: user-center
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31926
    - name: debug
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30730
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-center
  namespace: demo
spec:
  selector:
    matchLabels:
      app: user-center
  replicas: 1
  template:
    metadata:
      labels:
        app: user-center
    spec:
      containers:
        - name: user-center
          image: $REGISTRY/$HARBOR_NAMESPACE/$APP_NAME:SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: TZ
              value: Asia/Shanghai
